## The following fuctions below are used in creating a custom object that can store
#and caches maatrix and its inverse.

## makeCacheMatrix is a function that creates a matrix
# and is also the first function


makeCacheMatrix <- function(x = matrix()) {
        
        
i <- NULL
  set <- function(y) {
          x <<- y
          i <<- NULL
  }
  get <- function() x
  setInverse <- function(inverse) i <<- inverse
  getInverse <- function() i
  list(set = set,
       get = get,
       setinverse = setinverse,
       getinverse = getinverse)

}

#This function would be able to compute the inverse of the specific "matrix" that has been generated by makeCache matrix.
# If the inverse is now been calculated, CacheSolve would retrieve it from the cache.

cacheSolve <- function(x, ...) {
         i <- x$getinverse()
  if (!is.null(i)) {
          message("getting cached data")
          return(i)
  }
  data <- x$get()
  i <- solve(data, ...)
  x$setinverse(i)
  i
        
}
