## The following fuctions below are used in creating a custom object that can store
#and caches maatrix and its inverse.

## makeCacheMatrix is a function that creates a matrix
# and is considered as the first function in this series of code

makeCacheMatrix <- function(x = matrix()) {
          
value <- NULL
  set <- function(first_function) {
          second_function <<- first_function
          value <<- NULL
  }
  get <- function() second_function
  setInverse <- function(function_inverse) i <<- function_inverse
  getInverse <- function() value
        
  list(set = set,
       get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}

#This function would be able to compute the inverse of the specific "matrix" that has been generated by makeCache matrix.
# If the inverse is now been calculated, CacheSolve would retrieve it from the cache.

cacheSolve <- function(x, ...) {
         value <- x$getinverse()
  if (!is.null(value)) {
          message("providing cached data")
          return(value)
  }
  data <- x$get()
  value <- solve(data, ...)
  x$setinverse(value)
  value
        
}
